<?php

namespace App\Support;

use App\Models\User;
use Illuminate\Support\Facades\Cache;

/**
 * What the entry QR code actually contains. It used to be the user's
 * permanent UUID — a bearer token: anyone with a screenshot of it could walk
 * in as that person, forever. Now the code is
 * `{qr_code}.{expiry}.{nonce}.{signature}` (signed with the app key), valid for
 * one minute, regenerated by the customer's phone every few seconds. A
 * screenshot is useless almost immediately, and each token can be redeemed for
 * entry only once.
 */
class EntryToken
{
    public const TTL_SECONDS = 60;

    /**
     * @return array{token: string, expires_in: int}
     */
    public static function issue(User $user): array
    {
        $expires = now()->getTimestamp() + self::TTL_SECONDS;
        $nonce = bin2hex(random_bytes(6));

        return [
            'token' => "{$user->qr_code}.{$expires}.{$nonce}.".self::signature($user->qr_code, $expires, $nonce),
            'expires_in' => self::TTL_SECONDS,
        ];
    }

    /**
     * The user a scanned code belongs to, or null if it's malformed, forged,
     * expired, or an old permanent-style code.
     */
    public static function resolve(string $token): ?User
    {
        $parts = explode('.', $token);

        if (count($parts) !== 4 || ! ctype_digit($parts[1])) {
            return null;
        }

        [$qrCode, $expires, $nonce, $signature] = $parts;

        if (! hash_equals(self::signature($qrCode, (int) $expires, $nonce), $signature)) {
            return null;
        }

        if ((int) $expires < now()->getTimestamp()) {
            return null;
        }

        return User::where('qr_code', $qrCode)->first();
    }

    /**
     * Whether this token was already redeemed for an entry.
     */
    public static function alreadyUsed(string $token): bool
    {
        return Cache::has(self::usedKey($token));
    }

    /**
     * Claims a token for one entry. False if it was already used — a second
     * scan of the same code (a screenshot shared in the same minute).
     */
    public static function claim(string $token): bool
    {
        return Cache::add(self::usedKey($token), true, self::TTL_SECONDS + 30);
    }

    private static function usedKey(string $token): string
    {
        return 'entry-token-used:'.hash('sha256', $token);
    }

    private static function signature(string $qrCode, int $expires, string $nonce): string
    {
        return rtrim(strtr(base64_encode(hash_hmac('sha256', "entry|{$qrCode}|{$expires}|{$nonce}", self::key(), true)), '+/', '-_'), '=');
    }

    private static function key(): string
    {
        return (string) config('app.key');
    }
}
